### ISSUE TITLE
Rim lighting breaks and turns "greenish"

### ISSUE THREAD

**Issue by endjui** [poiyomi/PoiyomiToonShader#36] opened 2022-08-25 13:13 UTC
Rim lighting randomly breaks and stops working. Re-importing the package did not help.

See image for reference.
![image](https://user-images.githubusercontent.com/45940015/186674310-13de46cb-7bdc-42d8-a982-6892f8e8324c.png)

**Comment by rrazgriz** [comment] 2023-04-10 04:08
This has been fixed as of 8.1.156. The old behavior (caused by a clamp) can be replicated by enabling "Clamp Intensity" for rim lighting, which defaults to off.

**Closed by rrazgriz** 2023-04-10 04:08 UTC
