### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by xArkailzx** [poiyomi/PoiyomiToonShader#40] opened 2023-04-26 21:46 UTC
I'm trying to compile a shader with the last Poiyomi update, but I get a ton of errors in the console.
Unity version: 2019.4.31f1
![image](https://user-images.githubusercontent.com/78084119/234710049-a3d1cdff-5d7d-4c47-966d-c4437c7f2f58.png)

**Comment by rrazgriz** [comment] 2023-04-27 07:26
This is generally caused by not removing the old shader files when upgrading; we recommend always deleting the `_PoiyomiShaders` folder before importing a new shader version. (closing, as it was discussed in chat)

**Closed by rrazgriz** 2023-04-27 07:26 UTC
